language: rust
services:
  - docker
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cd tests/ && bash run_tests.sh