[package]
name = "ff"
version = "1.1.0"
authors = ["xliiv <tymoteusz.jankowski@gmail.com>"]

[dependencies]
clap = "2.24"
tempdir = "0.3.4"
rust-ini = "0.9.*"
walkdir = "0.1"

[dependencies.fui]
version = "0.7"
default-features = false
features = ["termion-backend"]
